### ISSUE TITLE
init platform right after package installation

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-platform-modules-dell#3]
after package installed, it requires a reboot to finish platform init. sonic requires the platform init after package installation, it should not require a reboot.

**Comment by nirenjan** [comment]
I'm not able to reproduce the issue - with the latest sonic-broadcom.bin, I see the package getting installed and the platform initialization running right away on first boot.

**Comment by lguohan** [comment]
yes, you are right. close this issue.
